version: "3"
services:

  db:
    image: postgres:15
    container_name: sso_db
    restart: always
    env_file:
      "./postgres/.env"
    volumes:
      - sso-db-data:/var/lib/postgresql/data
    ports:
    - "5433:5433"


  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: sso_server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - "./go/.env"
    depends_on:
     - "db"

volumes:
  sso-db-data:
  sso-build: