version: "3"
services:

  db:
    image: postgres:15
    container_name: sso_db
    restart: always
    network_mode: "host"
    env_file:
      - "./postgres/.env"
    volumes:
      - sso-db-data:/var/lib/postgresql/data


  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: sso_server
    restart: always
    network_mode: "host"
    env_file:
      - "./go/.env"
    volumes:
      - sso-build:/tmp/build
    depends_on:
      - db

volumes:
  sso-build:
  sso-db-data:
